<span class="mapa">
	<p><a href="<?= "http://".$_SERVER['HTTP_HOST']."/ciudad" ?>">Turista</a></p>
</span>
<section>
	<table class="table">
		<tr>
			<th>Código</th>
			<th>Nombre</th>
			<th>Ap.Paterno</th>
			<th>Ap.Materno</th>
			<th>rfc</th>
			<th>telefono</th>
			<th>email</th>
			<th>direccion</th>
			<th>Editar</th>
			<th>Eliminar</th>
		</tr>
		<?php foreach($ciudades as $ciudad): ?>
			<tr>
				<td><?= $ciudad->codigo ?></td>
				<td><?= $ciudad->nombre ?></td>
				<td><?= $ciudad->apellidoPaterno ?></td>
				<td><?= $ciudad->apellidoMaterno ?></td>
				<td><?= $ciudad->rfc ?></td>
				<td><?= $ciudad->telefono ?></td>
				<td><?= $ciudad->email ?></td>
				<td><?= $ciudad->direccion ?></td>
				<td><a href="<?= "http://".$_SERVER['HTTP_HOST']."/ciudad/editar/" . $ciudad->codigo ?>">Editar</a></td>
				<td><a href="<?= "http://".$_SERVER['HTTP_HOST']."/ciudad/delete/" . $ciudad->codigo ?>">Eliminar</a></td>
			</tr>
		<?php endforeach; ?>
	</table>
</section>

