<?= $this->doctype() ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <title>SGRyH</title>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/estilos.css'))
        ?>
    </head>
    <body>
    	<div class="cuerpo">
    		<header>
    			<img src="<?=$this->basePath("img/encabezado.png") ?>">
    		</header>
        <aside id="col">
          <img src="<?= $this->basePath("img/col.png") ?>">
        </aside>
        <div class="container">
            <?= $this->content ?>
        </div>
        <footer id="pie">
    			<div id="texto"><small id="texto">Desarrollo de aplicaciones web 2016</small></div>
    		</footer>
    </body>
</html>
